### ISSUE TITLE
Same condition on if and else if

### ISSUE THREAD

**Issue by juanicotolengo** [imana97/parse-mobx#1]
Hi!

I started to use this lib, and found an issue just by inspecting the code.

Following [this link](https://github.com/imana97/parse-mobx/blob/c1c9c4d9a88fcaa2d25e62aa2170a938689d8155/index.js#L35), on the given if condition at the constructor, the next else if checks the same condition that the if, resulting in never getting in there.

**Comment by imana97** [comment]
thanks. Let me have a look

**Comment by imana97** [comment]
fixed https://github.com/imana97/parse-mobx/commit/d7d8987ae02bc5a02e3d9ebe29fd4caf01481f88
